version: '{build}'
build_script:
  - cmd: git submodule update --init --recursive

  - cmd: mkdir build-12 && cd build-12
  - cmd: cmake -G"Visual Studio 12" -DFOONATHAN_MEMORY_BUILD_TOOLS=OFF -DFOONATHAN_MEMORY_BUILD_EXAMPLES=OFF -DFOONATHAN_MEMORY_BUILD_TESTS=OFF ..\
  - cmd: cmake --build . -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

  - cmd: cd ..\ && mkdir build-14-debug && cd build-14-debug\
  - cmd: cmake -G"Visual Studio 14" -DCMAKE_BUILD_TYPE=Debug ..\
  - cmd: cmake --build . --config Debug -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: test\Debug\foonathan_memory_test.exe

  - cmd: cd ..\ && mkdir build-14-release && cd build-14-release\
  - cmd: cmake -G"Visual Studio 14" -DCMAKE_BUILD_TYPE=Release ..\
  - cmd: cmake --build . --config Release -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: test\Release\foonathan_memory_test.exe

